# Use root/example as user/password credentials
version: '3.1'

services:
  db:
    image: mysql:8.0.33
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cookbook
      MYSQL_USER: user
      MYSQL_PASSWORD: 1234
      MYSQL_CHARSET: utf8mb4
      MYSQL_COLLATION: utf8mb4_general_ci
      LANG: C.UTF-8
      TZ: "Europe/Berlin"
    ports:
      - "3306:3306"
    volumes:
      - ./database:/docker-entrypoint-initdb.d
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    restart: always
    environment:
      - PMA_ARBITRARY=0
      - PMA_HOST=db
    depends_on:
      - db
    ports:
      - "8080:80"

  cookbook_api:
    build: ./cookbook.webapi
    restart: always
    depends_on:
      - db
      - phpmyadmin
    ports:
      - "3500:3500"

  cookbook:
    build: ./cookbook
    restart: always
    depends_on:
      - cookbook_api
    ports:
      - "3000:3000"

volumes:
  db_data: