/*==============================================================*/
/* Table: RECIPES                                               */
/*==============================================================*/

INSERT INTO cookbook.recipes (name, description, steps, picture, rating, kcal)
VALUES
    ('Spaghetti Bolognese', 'Klassisches italienisches Nudelgericht mit Hackfleischsauce', '1. Nudeln kochen\n2. Hackfleisch anbraten\n3. Zwiebeln und Knoblauch hinzufügen\n4. Tomatensoße hinzufügen\n5. Alles zusammen servieren', 'https://images.eatsmarter.de/sites/default/files/styles/max_size/public/spaghetti-bolognese-original-59303.jpg', 4.5, 500),
    ('Caesar Salat', 'Beliebter Salat mit Römersalat, Croutons, Parmesan und Caesar-Dressing', '1. Salat waschen und zerkleinern\n2. Croutons in der Pfanne anrösten\n3. Parmesan reiben\n4. Dressing aus Olivenöl, Zitronensaft, Ei, Knoblauch und Anchovis herstellen\n5. Alles zusammenmischen', 'https://images.eatsmarter.de/sites/default/files/styles/max_size/public/roemersalat-mit-croutons-und-parmesan-caesar-salad-46701.jpg', 4.2, 350),
    ('Schokoladenkuchen', 'Leckerer Schokoladenkuchen mit Schokoglasur', '1. Teig aus Butter, Zucker, Eiern, Mehl, Kakao und Backpulver herstellen\n2. Teig in eine Kuchenform füllen\n3. Kuchen im Ofen bei 180 Grad Celsius ca. 30 Minuten backen\n4. Schokoladenglasur schmelzen und über den abgekühlten Kuchen geben', 'https://sarascupcakery.de/wp-content/uploads/2020/03/SchokoladenkuchenCSaraBertram080.jpg', 4.8, 400),
    ('Griechischer Salat', 'Klassischer griechischer Salat mit Tomaten, Gurken, Oliven, Feta und Olivenöl', '1. Tomaten und Gurken in Würfel schneiden\n2. Oliven halbieren\n3. Feta-Käse zerbröseln\n4. Alles zusammenmischen\n5. Mit Olivenöl beträufeln', 'https://image.essen-und-trinken.de/11850352/t/sb/v8/w1440/r1.7778/-/griechischer-salat-03a82e12aa3591e27fcb83ed25ca193c-griechischer-salat-jpg--18006-.jpg', 4.4, 250),
    ('Hühnchen-Curry', 'Würziges Hühnchencurry mit Gemüse und Basmatireis', '1. Hühnchen in Stücke schneiden und anbraten\n2. Zwiebeln und Knoblauch hinzufügen\n3. Gemüse (z.B. Paprika, Erbsen) hinzufügen\n4. Currypaste und Kokosmilch hinzufügen\n5. Alles köcheln lassen und mit Basmatireis servieren', 'https://www.einfachkochen.de/sites/einfachkochen.de/files/styles/full_width_tablet_4_3/public/2021-07/haehnchen_curry_kokosmilch_1_0.jpg', 4.6, 600);
